# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('Num_cont', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('Edad', models.IntegerField()),
                ('FechaNacimiento', models.DateField()),
                ('Telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('Domicilio', models.TextField()),
            ],
        ),
    ]
